package edu.uade.api.tpo;

import edu.uade.api.tpo.db.PersistenceModule;
import edu.uade.api.tpo.model.SistemaUsuarios;
import edu.uade.api.tpo.model.Usuario;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        //Init database
        PersistenceModule.getInstance();
        Usuario u = SistemaUsuarios.getInstance().buscarUsuario("flor");
        System.out.println(u);
    }
}
