package edu.uade.api.tpo;

import edu.uade.api.tpo.db.PersistenceModule;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        //Init database
        PersistenceModule.getInstance();
    }
}
